# fly.toml app configuration file generated for ig-post-scraper on 2023-09-24T21:06:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ig-post-scraper"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
